- package.json
- src/commands/hello.ts
- src/index.ts
- tslint.json
- yarn.lock
- I removed settings that were obviously react/relay/jsx settings from reaction, as well as a custom rules directory.
- I updated the existing commands in src, based on the new settings
- I added the rule `"no-shadowed-variable": false` because shadowing seems like a thing that is pretty inherent to using oclif
My current output from type-checking:
> Pull suitable prettier and tslint settings from reaction #FF

- .circleci/config.yml
This PR removes the dry-run flag so that the release branch will really deploy to npm.
> Publish for real

- package.json
- src/lib/gravity/index.ts
- yarn.lock
Adds a `Gravity` class that can be instantiated and supplied to any command. 
This class will know about token stuff and about details of how to construct an url, given a resource. I.e. turn `artwork/123abc` into `https://api.artsy.net/api/v1/artwork/123abc` and fetch it.
I made it stateful, thinking ahead to tokens, but maybe it doesn't need to be 🤷‍♂ 
In my WIP branch this gets used in a Command's `run` function as follows:
```js
async run() {
const gravity = new Gravity()
const response = await gravity.get(`something/123`)
if (response.status === 200) {
// do something with response.json()
} else {
// cry
}
}
```
> Add a Gravity fetching client

- .autorc
- .circleci/config.yml
This does two things: 
1. Simplifies the orb by using our pre-established orbs
2. Sets up `auto` for PR based releases. 
The first publish in a project can be a little weird sometimes, so I'll work through any issues that crop up. Otherwise, this should just make it a little easier for folks to contribute.
> Use orbs and setup auto PR for publishing

- .circleci/config.yml
Third time is the charm?
This adds a missing [context](https://circleci.com/docs/2.0/contexts/) which contains the environment variables needed for publishing.
> Add circleci context for publishing permissions

- package.json
- src/commands/identify.ts
- test/commands/identify.test.ts
- tslint.json
- yarn.lock
Adds an `identify` command to identify an Artist, Artwork or Partner based on its BSON id. This also demonstrates the oclif way of mocking network requests in the accompanying test.
Still supplying the token as an env var, till we get logins wired up.
> Add an `identify` command #FF

- README.md
- package.json
Closes #12.
Instead of publishing to `artsy-cli` on npm it'll publish  to `@artsy/cli`. 
I also updated the release documentation.
> Update project to publish to @artsy/cli

- src/commands/scheduled/standup-reminder.ts
- test/commands/scheduled/standup-reminder.test.ts
This fix was applied to the `on-call:next` command but needs to be ported here as well.
> fix: port opsgenie nextOnCall fix to standup-reminder

- package.json
- yarn.lock
New CLI version notifications via [this oclif plugin][1].
[1]: https://github.com/oclif/plugin-warn-if-update-available
```
$ artsy --help
›   Warning: @artsy/cli update available from 0.6.0 to 0.7.1.
```
> feat: warn when new CLI version available

- src/commands/identify.ts
- src/commands/login.ts
- src/commands/logout.ts
- src/commands/whoami.ts
- src/utils/gravity.ts
- test/commands/identify.test.ts
This also adds an `artsy whoami` command to verify logged in state.
Experimented with some oauth flows here and in https://github.com/artsy/eigen/pull/4467 during Future Friday last week.
#FutureFriday #FF
https://user-images.githubusercontent.com/123595/108740230-73052200-7503-11eb-981c-2b00bb69ce55.mov
> feat: update login to use OAuth flow

- src/commands/scheduled/next-on-call.ts
- src/commands/scheduled/standup-reminder.ts
- src/utils/slack.ts
- test/commands/scheduled/next-on-call.test.ts
- test/commands/scheduled/standup-reminder.test.ts
Split these messages so we can send them on different schedules.
> chore: split standup reminder from upcoming on-call shift reminder

- package.json
- src/commands/scheduled/recently-published.ts
- test/commands/scheduled/recently-published.test.ts
- test/fixtures/podcast.xml
- yarn.lock
Will address #26 eventually.
For now it's emitting slack blocks for summarizing the most recent podcast episode, but I'm planning on adding the blog summary as part of this PR.
> [WIP] feat: command for summarizing recent blog articles & podcast episodes

- package.json
- yarn.lock
Addresses this CI error:
```
node_modules/rss-parser/index.d.ts(1,25): error TS7016: Could not find a declaration file for module 'xml2js'. '/home/circleci/project/node_modules/xml2js/lib/xml2js.js' implicitly has an 'any' type.
Try `npm install @types/xml2js` if it exists or add a new declaration (.d.ts) file containing `declare module 'xml2js';`
```
https://app.circleci.com/pipelines/github/artsy/cli/223/workflows/33480dcc-99af-4989-9afe-ef19cbf8fea2/jobs/594
> fix: add @types/xml2js to fix tsc -b

- .circleci/config.yml
- package.json
- src/commands/scheduled/recently-published.ts
- test/commands/scheduled/recently-published.test.ts
- test/fixtures/feed.xml
- test/mocha.opts
- tsconfig.json
Adds some blocks to promote our most recent blog posts. Addresses #26.
Looks like this:
I opted to do a "days since" counter for blog posts because I secretly hope it will let people know when it's been a looonnngggg time since we published.
> feat: promote most recent blog posts in scheduled:recently-published command.

- .circleci/config.yml
Hoping that this configures the artsy/yarn orb to use the NodeJS v12 execution environment from the updated artsy/node orb.
> chore: configure node orb

- .circleci/config.yml
Looks like we have another auto/publish-canary job which targets NodeJS v12.
> chore: use auto/publish-canary

- src/__generated__/graphql.ts
- src/commands/audit/repositories.ts
- src/queries/repositories.graphql
- test/commands/audit/repositories.test.ts
- test/fixtures/repositories.ts
Fetch and display information for repositories within the Artsy GitHub organization.
Initially to be used to aid in our switch from a default branch of `master` to `main`.
Usage:
```
$ artsy audit:repositories
$ artsy audit:repositories --csv
$ artsy audit:repositories --csv --default-branch=main
$ artsy audit:repositories --csv --default-branch=main --pushed=">2021-05-01"
```
@kajatiger Thought this might be a useful command to help with https://github.com/artsy/README/pull/387!
> feat: add audit:repositories command

- package.json
- yarn.lock
This PR reverts https://github.com/artsy/cli/commit/7ac8ef3176021ba8e2f2e916d4675598a09f8122 which broke the publish script:
**CircleCI error log**
https://app.circleci.com/pipelines/github/artsy/cli/451/workflows/2ce244d9-a048-469b-bc53-f479755db283/jobs/1331
```
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error yargs@17.0.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code exit status 1
CircleCI received exit code 1
```
> Revert chore(deps-dev): bump @graphql-codegen/cli from 1.21.4 to 1.21.5

- src/commands/scheduled/recently-published.ts
- test/commands/scheduled/recently-published.test.ts
I moved writing office hours a few weeks ago to be more friendly to engineers in Europe. This updates our slack reminder to tell people the correct info!
> chore: update writing office hours time

- src/commands/scheduled/recently-published.ts
- test/commands/scheduled/recently-published.test.ts
The slack updates for Artsy Engineering Radio are out of date! Because I forgot to update the feed URL here 😅 😬 
This updates it to the correct location, so that we can see in #dev that the podcast is crushing it.
Collaboration with @mdole, @annacarey, and @shaq31415926
> chore: update artsy engineering radio RSS source

- package.json
- yarn.lock
Downgrade ts-node to keep compatibility with Node v10.
> deps(dev): downgrade ts-node

- .autorc
- .circleci/config.yml
The default auto version is specified in our Circle CI orb [here][0]. This is used to determine which version of the tool we download into the Circle CI container.
I'm hoping that we can override the orb's environment variable by specifying a value here in the project's config.
[0]: https://github.com/artsy/orbs/blob/e480ac7adbbe923d58e5726d6c34b0ce3eb63815/src/auto/auto.yml#L17
> chore(auto): pin to more recent auto version

- src/commands/scheduled/recently-published.ts
- test/commands/scheduled/recently-published.test.ts
- test/fixtures/podcast.xml
After #232 the "most recent podcast" being touted was the first episode ever; because the buzzsprout RSS feed is sorted newest to oldest, while our self-hosted feed was oldest to newest. Oops!
> fix: buzzsprout's rss feed has recent episodes at top, not bottom

- package.json
- src/commands/scheduled/recently-published.ts
- test/commands/scheduled/recently-published.test.ts
- yarn.lock
Cleans up a few things for the `scheduled:recently-published` task, for the weekly update that gets posted to slack. 
1. Fixes a test that was failing locally due to time zones & blog rss dates not having times
2. Replaces apple/google podcast URLs with buzzsprout
3. Links episodes directly to the buzzsprout page
4. Cleans up the episode description, which I noticed after #232 was not actually markdown (buzzsprout gives us raw HTML)
(The gray "Artsy Engineering" next to "Jul 8, 2021" is the author of the episode...I think we've not been filling it in on buzzsprout when we upload episodes, and it defaults to our account name.)
> feat: improve recent podcast summary

- src/commands/scheduled/next-on-call.ts
- test/commands/scheduled/next-on-call.test.ts
The `Support` playbook was recently renamed to `Incident Handling`
> fix: set correct on call playbook url

- .dockerignore
- Dockerfile
- bin/docker-run
- scripts/test.py
- src/commands/python/test.ts
- Dockerfile to build an image including Node, Python, and project dependencies
- bin/docker-run script to execute CLI commands within a Docker container
- python:test command as a POC
To try it out, you can run the following commands:
```
$ docker build -t artsy/cli .
$ bin/docker-run python:test
```
Since I also have Python installed locally, I'm also able to run the task using the local CLI runner:
```
$ bin/run python:test
```
> feat: add POC for commands which execute python scripts

- README.md
- src/commands/identify.ts
- src/commands/login.ts
- src/commands/logout.ts
- src/commands/whoami.ts
- src/config.ts
- src/utils/gravity.ts
- test/setup-mocha.ts
This PR changes how we do configuration for artsy-cli - rather than using ENV vars it seeks to use a JSON file. At this point I'm storing the Gravity id/secret in there and then if you login the associated access token. If we like this direction then we could move more things like the creds for Slack/GitHub/OpsGenie. I had to draw a line somewhere or else I'd still be refactoring things! 😝 
The changes here are breaking. It would mean that existing installs with a plaintext file at `~/.config/artsy` would need to be updated like so:
```
$ rm ~/.config/artsy
$ mkdir ~/.config/artsy
$ aws s3 cp s3://artsy-citadel/dev/artsy-cli-config.json ~/.config/artsy/config.json
```
And then the person could login again. Maybe that means I should bump the version?
> feat: Use more standard config approach

- CONTRIBUTING.md
- package.json
- src/commands/jwt.ts
- test/commands/jwt.test.ts
- yarn.lock
Adds a safer alternative to web-based JWT decoders.
The JWT never leaves your terminal, and is base64 decoded without any extra dependencies.
Example with a fake token:
```sh
$ artsy jwt eyJhbGciOiJ0ZXN0In0.eyJpc3MiOiJTa3luZXQiLCJpYXQiOjE2NDg2NTIyNTcsInJvbGVzIjoiaGF4MHIifQ.loljkjk 
{ alg: 'test' }
{ iss: 'Skynet', iat: 1648652257, roles: 'hax0r' }
```
> feat: add 'jwt' command to decode an access token locally

- src/commands/scheduled/facilitate-incident-review.ts
This refactors the helper used to set the default date and time when performing an opsgenie engineering schedule lookup.
@joeyAghion we discussed Thursday as better day to use but it occurred to me that in some rare cases, an engineer may need to schedule OOO on Thursday tho the schedule may not be up to date at the time the lookup is performed. I chose to keep it on Wednesday but shift the hours by enough to compensate for daylight savings time changes.
Happy to change this of course.
> refactor: FacilitateIncidentReview date helper

- src/commands/scheduled/facilitate-incident-review.ts
This expands the `FacilitateIncidentReview` command to support control of execution via ENV var `Dates` (in JSON string format).
`DATES` ENV var will be used to set a starting point via `baseDate` field and the command will exit early on the weeks that are "_Off weeks_" for Incident Reviews. In addition, an `exceptions` field can be set which would allow for whitelisting "Off week" dates.
As this command is going to be executed via Joule (bot) github actions, the intent is to allow for (_some_) control of execution based on dates without having to make code changes. In cases when the Incident Review meeting is canceled due to a Hackathon or an additional meeting is added to catch up, modifying the ENV var in Joule project will allow for some control of this cron-based command.
> feat: FacilitateIncidentReview supports off week calculation

- README.md
As per https://github.com/artsy/README/pull/530, this updates setup to pull shared configuration from its new, simpler location.
> chore: simplify S3 path for shared configuration

- src/clients/gravity.ts
- src/commands/login.ts
- src/commands/logout.ts
- src/config.ts
Adds basic support for:
- logging into staging
- switching between staging and prod in Gravity client
- clearing out tokens from both environments
e.g:
`artsy login --staging`
will open the staging login flow and set a staging token in the config. 
Needed this for another project but seems generally useful in the meantime! Let me know any feedback
Based on this discussion from initial implementation: https://github.com/artsy/cli/pull/62/files#r580642852
> feat: support staging login and gravity env

- src/commands/scheduled/sapphire-next-on-call-retro.ts
- src/commands/scheduled/sapphire-next-on-call.ts
- test/commands/scheduled/sapphire-next-on-call-retro.test.ts
- test/commands/scheduled/sapphire-next-on-call.test.ts
Adding two reminders for Sapphire ceremony rotations by calling opsgenie and sending Slack messages. These will need to be scheduled in joules.
> feat: add Sapphire ceremony reminders to schedules

- src/commands/scheduled/next-on-call.ts
- test/commands/scheduled/next-on-call.test.ts
The incident-handling page was moved to notion. This updates NextOnCall to link to the correct location. Currently link returns 404.
> chore: update next on call incident handling link
